app:
  domain: "217.154.239.23"
  port: "14743"
  uuid: "3f601ae3-ef06-436c-9a70-eea4b929ef0a"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: "wispbyte.699689.xyz"
  argo-token: "eyJhIjoiNTk4NTkzZTA0ZjcyODYxYzg4ZWEzNzEyM2M5NjI5YzgiLCJ0IjoiODI2NmQ5OTYtYzNjMy00NzBhLTgxYWQtMjc1NzRhYTNhOGM2IiwicyI6Ik1UTXdNMlF4WWpndE9EVTVOQzAwWWpjMExXRTFZVFl0TXpnM04yVXpPREZpTTJSbCJ9"
  remarks-prefix: "wispbyte"
